### ISSUE TITLE
Generated CBOM always empty

### ISSUE THREAD

**Issue by wlargou** [IBM/sonar-cryptography#111]
Hi,

I have tried with different java applications, using the SonarQube plugin, the CBOM is generated but always with the following output :

{
  "bomFormat" : "CycloneDX",
  "specVersion" : "1.6",
  "serialNumber" : "urn:uuid:303cb601-1ab3-4f38-8be5-803550e2e0c6",
  "version" : 1,
  "metadata" : {
    "timestamp" : "2024-08-21T12:42:22Z",
    "tools" : {
      "services" : [
        {
          "provider" : {
            "name" : "IBM"
          },
          "name" : "Sonar Cryptography Plugin",
          "version" : "1.2.0"
        }
      ]
    }
  },
  "dependencies" : [ ]
}

I suspected first that it found nothing in my code so I added the following :

MessageDigest md = null;
        try {
            md = MessageDigest.getInstance("SHA-256");
        } catch (NoSuchAlgorithmException e) {
            throw new RuntimeException(e);
        }
        
As In the CBOM viewer example it should have picked this.

Maybe I'm missing something

**Comment by hugoqnc** [comment]
Hi @wlargou, indeed the example you provided should be detected by our scanner.
- What is your SonarQube version? Currently, a change in recent SonarQube versions (`10.5.0` and above) prevents our plugin to report any findings, which at first glance sounds like the problem you have.
- Otherwise, did you make sure to activate our inventory rule in your quality profile, and to use this quality profile for your scan?

If you known that the problem does not come from these two points, could please try to scan this [sample repo](https://github.com/Mastercard/client-encryption-java), and let me known if you still don't see any results?

**Comment by wlargou** [comment]
Indeed i'm using latest version 10.6.0.92116. As for the activation, it happened differently i guess new with this version, i only dropped the jar and restarted, and in the homescreen it said if i want to install the plugin. (There is no activate button i think in newer versions)

<img width="1190" alt="image" src="https://github.com/user-attachments/assets/4a0f98da-e2f8-4dfb-9098-33f3ebb93162">


I have just tried with 10.4 same behavior. For the sample repo it doesn't build :

gpg: no default secret key: No secret key
gpg: signing failed: No secret key
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Skipping client-encryption
[INFO] This project has been banned from the build due to previous failures.
[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.309 s
[INFO] Finished at: 2024-08-21T20:06:29Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-gpg-plugin:3.1.0:sign (sign-artifacts) on project client-encryption: Exit code: 2 -> [Help 1]



I think i need to get certificate from mastercard developer first.

What's the versions of SonarQube you have tested with ? Or is there any other simple sample i can test.

Thank you for the help

**Comment by wlargou** [comment]
I see that you have updated the docker-compose to point specifically to 10.4, do you have any other sample I can test. I have tested all the versions (nearly) down to 9.9 (which is the minimal supported by the plugin).

Thank you

**Comment by wlargou** [comment]
I have tried created a brand new project : 

Java : openjdk version "21.0.3"
Maven : Apache Maven 3.9.6
SonarVersion : 10.2.0.77647

Plugin :
<img width="1041" alt="image" src="https://github.com/user-attachments/assets/e04d93b1-fd18-4c65-9b80-2d39997d0f23">

Here is the code I have :

public class CryptoApplication {

	public static void main(String[] args) throws NoSuchAlgorithmException {

		MessageDigest md = null;
        try {
            md = MessageDigest.getInstance("SHA-256");
        } catch (NoSuchAlgorithmException e) {
            throw new RuntimeException(e);
        }
		System.out.println("Lenght : " + md.getAlgorithm().length() + "Algorithm :" + getKeyFactory("ECDSA").toString());
		SpringApplication.run(CryptoApplication.class, args);


	}

	public static KeyFactory getKeyFactory(String algorithm) throws NoSuchAlgorithmException {
		if("ECDSA".equals(algorithm)) {
			// ECDSA is not a listed JavaSE KeyFactory algorithm
			// see https://docs.oracle.com/en/java/javase/11/docs/specs/security/standard-names.html#cipher-algorithm-names
			algorithm = "EC";
		}
		return KeyFactory.getInstance(algorithm);
	}


	public static byte[] computeArtifactBindingIdentifier(String identifierFrom) {
		try {
			MessageDigest sha1Digester = MessageDigest.getInstance("SHA-1");
			return sha1Digester.digest(identifierFrom.getBytes(StandardCharsets.UTF_8));
		} catch (NoSuchAlgorithmException e) {
			throw new RuntimeException("JVM does not support required cryptography algorithms: SHA-1/SHA1PRNG.", e);
		}
	}

}



And here is a command to scan with sonar : 

mvn clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:4.0.0.4121:sonar \
  -Dsonar.projectKey=Test4 \
  -Dsonar.projectName='Test4' \
  -Dsonar.host.url=http://<MYIP>:9000 \
  -Dsonar.token=<MYTOKEN>
  
Here is the logs :

[INFO] Scanning for projects...
[INFO] 
[INFO] -------------------------< com.example:crypto >-------------------------
[INFO] Building crypto 0.0.1-SNAPSHOT
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- clean:3.3.2:clean (default-clean) @ crypto ---
[INFO] Deleting /Users/largouwalid/Downloads/crypto/target
[INFO] 
[INFO] --- resources:3.3.1:resources (default-resources) @ crypto ---
[INFO] Copying 1 resource from src/main/resources to target/classes
[INFO] Copying 0 resource from src/main/resources to target/classes
[INFO] 
[INFO] --- compiler:3.13.0:compile (default-compile) @ crypto ---
[INFO] Recompiling the module because of changed source code.
[INFO] Compiling 1 source file with javac [debug parameters release 17] to target/classes
[INFO] 
[INFO] --- resources:3.3.1:testResources (default-testResources) @ crypto ---
[INFO] skip non existing resourceDirectory /Users/largouwalid/Downloads/crypto/src/test/resources
[INFO] 
[INFO] --- compiler:3.13.0:testCompile (default-testCompile) @ crypto ---
[INFO] Recompiling the module because of changed dependency.
[INFO] Compiling 1 source file with javac [debug parameters release 17] to target/test-classes
[INFO] 
[INFO] --- surefire:3.2.5:test (default-test) @ crypto ---
[INFO] Using auto detected provider org.apache.maven.surefire.junitplatform.JUnitPlatformProvider
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.example.crypto.CryptoApplicationTests
12:46:08.634 [main] INFO org.springframework.test.context.support.AnnotationConfigContextLoaderUtils -- Could not detect default configuration classes for test class [com.example.crypto.CryptoApplicationTests]: CryptoApplicationTests does not declare any static, non-private, non-final, nested classes annotated with @Configuration.
12:46:08.694 [main] INFO org.springframework.boot.test.context.SpringBootTestContextBootstrapper -- Found @SpringBootConfiguration com.example.crypto.CryptoApplication for test class com.example.crypto.CryptoApplicationTests

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/

 :: Spring Boot ::                (v3.3.2)

2024-08-22T12:46:08.950+01:00  INFO 41734 --- [crypto] [           main] c.example.crypto.CryptoApplicationTests  : Starting CryptoApplicationTests using Java 21.0.3 with PID 41734 (started by largouwalid in /Users/largouwalid/Downloads/crypto)
2024-08-22T12:46:08.951+01:00  INFO 41734 --- [crypto] [           main] c.example.crypto.CryptoApplicationTests  : No active profile set, falling back to 1 default profile: "default"
2024-08-22T12:46:09.265+01:00  INFO 41734 --- [crypto] [           main] c.example.crypto.CryptoApplicationTests  : Started CryptoApplicationTests in 0.489 seconds (process running for 1.064)
WARNING: A JVM TI agent has been loaded dynamically (/Users/largouwalid/.m2/repository/net/bytebuddy/byte-buddy-agent/1.14.18/byte-buddy-agent-1.14.18.jar=)
WARNING: If a serviceability tool is in use, please run with -XX:+EnableDynamicAgentLoading to hide this warning
WARNING: If a serviceability tool is not in use, please run with -Djdk.instrument.traceUsage for more information
WARNING: Dynamic loading of agents will be disallowed by default in a future release
WARNING: A Java agent has been loaded dynamically (/Users/largouwalid/.m2/repository/net/bytebuddy/byte-buddy-agent/1.14.18/byte-buddy-agent-1.14.18.jar)
WARNING: If a serviceability tool is in use, please run with -XX:+EnableDynamicAgentLoading to hide this warning
WARNING: If a serviceability tool is not in use, please run with -Djdk.instrument.traceUsage for more information
WARNING: Dynamic loading of agents will be disallowed by default in a future release
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.760 s -- in com.example.crypto.CryptoApplicationTests
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] 
[INFO] --- jar:3.4.2:jar (default-jar) @ crypto ---
[INFO] Building jar: /Users/largouwalid/Downloads/crypto/target/crypto-0.0.1-SNAPSHOT.jar
[INFO] 
[INFO] --- spring-boot:3.3.2:repackage (repackage) @ crypto ---
[INFO] Replacing main artifact /Users/largouwalid/Downloads/crypto/target/crypto-0.0.1-SNAPSHOT.jar with repackaged archive, adding nested dependencies in BOOT-INF/.
[INFO] The original artifact has been renamed to /Users/largouwalid/Downloads/crypto/target/crypto-0.0.1-SNAPSHOT.jar.original
[INFO] 
[INFO] -------------------------< com.example:crypto >-------------------------
[INFO] Building crypto 0.0.1-SNAPSHOT
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- sonar:4.0.0.4121:sonar (default-cli) @ crypto ---
[INFO] 12:46:10.746 Java 21.0.3 Eclipse OpenJ9 (64-bit)
[INFO] 12:46:10.746 Mac OS X 14.1 (aarch64)
[INFO] 12:46:10.821 User cache: /Users/largouwalid/.sonar/cache
[INFO] 12:46:11.076 Communicating with SonarQube Server 10.2.0.77647
[INFO] 12:46:11.084 Default locale: "en_US", source code encoding: "UTF-8"
[INFO] 12:46:11.387 Load global settings
[INFO] 12:46:11.646 Load global settings (done) | time=260ms
[INFO] 12:46:11.647 Server id: 243B8A4D-AZF2r7nQLZP9mRSQKJly
[INFO] 12:46:11.650 User cache: /Users/largouwalid/.sonar/cache
[INFO] 12:46:11.653 Load/download plugins
[INFO] 12:46:11.653 Load plugins index
[INFO] 12:46:11.781 Load plugins index (done) | time=128ms
[INFO] 12:46:11.845 Load/download plugins (done) | time=192ms
[INFO] 12:46:11.993 Sonar Cryptography initialized in context (SONARQUBE)
[INFO] 12:46:12.217 Process project properties
[INFO] 12:46:12.222 Process project properties (done) | time=5ms
[INFO] 12:46:12.224 Execute project builders
[INFO] 12:46:12.225 Execute project builders (done) | time=1ms
[INFO] 12:46:12.230 Project key: Test4
[INFO] 12:46:12.230 Base dir: /Users/largouwalid/Downloads/crypto
[INFO] 12:46:12.230 Working dir: /Users/largouwalid/Downloads/crypto/target/sonar
[INFO] 12:46:12.234 Load project settings for component key: 'Test4'
[INFO] 12:46:12.341 Load project settings for component key: 'Test4' (done) | time=107ms
[WARNING] 12:46:12.446 SCM provider autodetection failed. Please use "sonar.scm.provider" to define SCM of your project, or disable the SCM Sensor in the project settings.
[INFO] 12:46:12.451 Load quality profiles
[INFO] 12:46:12.584 Load quality profiles (done) | time=133ms
[INFO] 12:46:12.591 Load active rules
[INFO] 12:46:16.469 Load active rules (done) | time=3878ms
[INFO] 12:46:16.473 Load analysis cache
[INFO] 12:46:16.578 Load analysis cache (198 bytes) | time=105ms
[INFO] 12:46:16.619 Load project repositories
[INFO] 12:46:16.723 Load project repositories (done) | time=104ms
[INFO] 12:46:16.748 Indexing files...
[INFO] 12:46:16.748 Project configuration:
[INFO] 12:46:16.763 3 files indexed
[INFO] 12:46:16.764 Quality profile for java: Sonar way
[INFO] 12:46:16.764 Quality profile for xml: Sonar way
[INFO] 12:46:16.764 ------------- Run sensors on module Test4
[INFO] 12:46:16.767 Sonar Cryptography initialized in context (SONARQUBE)
[INFO] 12:46:16.839 Load metrics repository
[INFO] 12:46:16.945 Load metrics repository (done) | time=106ms
[INFO] 12:46:17.947 Sensor JavaSensor [java]
[INFO] 12:46:17.950 Configured Java source version (sonar.java.source): 17, preview features enabled (sonar.java.enablePreview): false
[INFO] 12:46:17.968 Server-side caching is enabled. The Java analyzer will not try to leverage data from a previous analysis.
[INFO] 12:46:17.969 Using ECJ batch to parse 1 Main java source files with batch size 214 KB.
[INFO] 12:46:18.156 Starting batch processing.
[INFO] 12:46:18.492 The Java analyzer cannot skip unchanged files in this context. A full analysis is performed for all files.
[INFO] 12:46:18.712 100% analyzed
[INFO] 12:46:18.712 Batch processing: Done.
[INFO] 12:46:18.712 Did not optimize analysis for any files, performed a full analysis for all 1 files.
[INFO] 12:46:18.713 Using ECJ batch to parse 1 Test java source files with batch size 214 KB.
[INFO] 12:46:18.715 Starting batch processing.
[INFO] 12:46:18.752 100% analyzed
[INFO] 12:46:18.752 Batch processing: Done.
[INFO] 12:46:18.752 Did not optimize analysis for any files, performed a full analysis for all 1 files.
[INFO] 12:46:18.752 No "Generated" source files to scan.
[INFO] 12:46:18.753 Sensor JavaSensor [java] (done) | time=805ms
[INFO] 12:46:18.753 Sensor JaCoCo XML Report Importer [jacoco]
[INFO] 12:46:18.753 'sonar.coverage.jacoco.xmlReportPaths' is not defined. Using default locations: target/site/jacoco/jacoco.xml,target/site/jacoco-it/jacoco.xml,build/reports/jacoco/test/jacocoTestReport.xml
[INFO] 12:46:18.754 No report imported, no coverage information will be imported by JaCoCo XML Report Importer
[INFO] 12:46:18.754 Sensor JaCoCo XML Report Importer [jacoco] (done) | time=1ms
[INFO] 12:46:18.754 Sensor CSS Rules [javascript]
[INFO] 12:46:18.754 No CSS, PHP, HTML or VueJS files are found in the project. CSS analysis is skipped.
[INFO] 12:46:18.754 Sensor CSS Rules [javascript] (done) | time=0ms
[INFO] 12:46:18.754 Sensor C# Project Type Information [csharp]
[INFO] 12:46:18.754 Sensor C# Project Type Information [csharp] (done) | time=0ms
[INFO] 12:46:18.754 Sensor C# Analysis Log [csharp]
[INFO] 12:46:18.763 Sensor C# Analysis Log [csharp] (done) | time=9ms
[INFO] 12:46:18.763 Sensor C# Properties [csharp]
[INFO] 12:46:18.763 Sensor C# Properties [csharp] (done) | time=0ms
[INFO] 12:46:18.763 Sensor SurefireSensor [java]
[INFO] 12:46:18.764 parsing [/Users/largouwalid/Downloads/crypto/target/surefire-reports]
[INFO] 12:46:18.801 Sensor SurefireSensor [java] (done) | time=38ms
[INFO] 12:46:18.802 Sensor HTML [web]
[INFO] 12:46:18.803 Sensor HTML [web] (done) | time=1ms
[INFO] 12:46:18.803 Sensor XML Sensor [xml]
[INFO] 12:46:18.808 1 source file to be analyzed
[INFO] 12:46:18.894 1/1 source file has been analyzed
[INFO] 12:46:18.894 Sensor XML Sensor [xml] (done) | time=91ms
[INFO] 12:46:18.894 Sensor TextAndSecretsSensor [text]
[INFO] 12:46:19.111 3 source files to be analyzed
[INFO] 12:46:19.117 3/3 source files have been analyzed
[INFO] 12:46:19.117 Sensor TextAndSecretsSensor [text] (done) | time=223ms
[INFO] 12:46:19.117 Sensor VB.NET Project Type Information [vbnet]
[INFO] 12:46:19.118 Sensor VB.NET Project Type Information [vbnet] (done) | time=1ms
[INFO] 12:46:19.118 Sensor VB.NET Analysis Log [vbnet]
[INFO] 12:46:19.127 Sensor VB.NET Analysis Log [vbnet] (done) | time=9ms
[INFO] 12:46:19.127 Sensor VB.NET Properties [vbnet]
[INFO] 12:46:19.127 Sensor VB.NET Properties [vbnet] (done) | time=0ms
[INFO] 12:46:19.127 Sensor IaC Docker Sensor [iac]
[INFO] 12:46:19.129 0 source files to be analyzed
[INFO] 12:46:19.174 0/0 source files have been analyzed
[INFO] 12:46:19.174 Sensor IaC Docker Sensor [iac] (done) | time=47ms
[INFO] 12:46:19.176 ------------- Run sensors on project
[INFO] 12:46:19.211 Sensor Analysis Warnings import [csharp]
[INFO] 12:46:19.212 Sensor Analysis Warnings import [csharp] (done) | time=1ms
[INFO] 12:46:19.212 Sensor Zero Coverage Sensor
[INFO] 12:46:19.215 Sensor Zero Coverage Sensor (done) | time=3ms
[INFO] 12:46:19.215 Sensor Java CPD Block Indexer
[INFO] 12:46:19.225 Sensor Java CPD Block Indexer (done) | time=10ms
[INFO] 12:46:19.227 SCM Publisher No SCM system was detected. You can use the 'sonar.scm.provider' property to explicitly specify it.
[INFO] 12:46:19.228 CPD Executor Calculating CPD for 1 file
[INFO] 12:46:19.231 CPD Executor CPD calculation finished (done) | time=3ms
[INFO] 12:46:19.290 Analysis report generated in 55ms, dir size=147.3 kB
[INFO] 12:46:19.302 Analysis report compressed in 12ms, zip size=22.3 kB
[INFO] 12:46:19.436 Analysis report uploaded in 133ms
[INFO] 12:46:19.437 ANALYSIS SUCCESSFUL, you can find the results at: http://52.249.222.239:9000/dashboard?id=Test4
[INFO] 12:46:19.437 Note that you will be able to access the updated dashboard once the server has processed the submitted analysis report
[INFO] 12:46:19.437 More about the report processing at http://52.249.222.239:9000/api/ce/task?id=AZF56LVELZP9mRSQKXKx
[INFO] 12:46:19.440 Executing post-job 'Output generation'
[INFO] 12:46:19.605 CBOM was successfully generated 'cbom.json'.
[INFO] 12:46:19.612 Analysis total time: 7.684 s
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  13.194 s
[INFO] Finished at: 2024-08-22T12:46:19+01:00
[INFO] ------------------------------------------------------------------------


And finally the generated CBOM :

{
  "bomFormat" : "CycloneDX",
  "specVersion" : "1.6",
  "serialNumber" : "urn:uuid:227e449d-444a-4dd7-b5e3-3580f576ec62",
  "version" : 1,
  "metadata" : {
    "timestamp" : "2024-08-22T11:46:19Z",
    "tools" : {
      "services" : [
        {
          "provider" : {
            "name" : "IBM"
          },
          "name" : "Sonar Cryptography Plugin",
          "version" : "1.2.0"
        }
      ]
    }
  },
  "dependencies" : [ ]
}

**Comment by wlargou** [comment]
Finally found the issue, so the plugin is not activated by default on default Java Quality Profile, so here are the steps I followed for future reference (or maybe add to the docs) : 

1 - Create a copy of the Java Profile (since you cannot activate the plugin on the default one)
<img width="1203" alt="image" src="https://github.com/user-attachments/assets/300c30f0-627b-40ee-94bc-68d4f05d910d">

2 - Provide a name : 

<img width="607" alt="image" src="https://github.com/user-attachments/assets/a7a17fa6-34a9-4d46-9187-9a84ccf6df8f">

3 - Go to Rule Breakdown -> Software Qualities -> Maintainability and click on the inactive (135 in this case) :

<img width="517" alt="image" src="https://github.com/user-attachments/assets/1b2a4152-b031-4c65-8643-0fa719eca8de">

4 - Search for Rule Crypto and activate : 

<img width="1647" alt="image" src="https://github.com/user-attachments/assets/4e6eea9d-0fa3-4e90-8377-e90474a19743">

<img width="556" alt="image" src="https://github.com/user-attachments/assets/3ecaa43d-c76a-470c-8a91-a1e1bcaa2132">

5 - Go to your project and for Settings choose Quality Profiles :

<img width="1712" alt="image" src="https://github.com/user-attachments/assets/224c5a6b-5add-433e-afc8-39793f859a98">

6 - Either add language or edit exiting one for Java to use the new Profile :

<img width="1721" alt="image" src="https://github.com/user-attachments/assets/c963d184-642f-4a34-b550-24be5697757f">

 7 - Rerun the scan

**Comment by hugoqnc** [comment]
@wlargou Yes, happy that it works for you now! I am writing a more detailed guide including these instructions which will be added to the repo soon, so it can help others :)
