### ISSUE TITLE
Update the Python implementation with latest good practices

### ISSUE THREAD

**Issue by hugoqnc** [IBM/sonar-cryptography#30]
The language support for Python was written before some general changes were introduced.
It should therefore be updated to take advantage of these changes, to have a more coherent and maintainable implementation.
- Rewrite how values are resolved to make it closer to the Java implementation
    - Use `ValueActionFactory` to capture the function names 
- Refactor the translation similarly to what was done with `JavaTranslationProcess`
    - Add a reorganization layer _if necessary_

**Comment by n1ckl0sk0rtge** [comment]
Fixed by #106, #109, #115, #119
