### ISSUE TITLE
Logging of scan statistics when and after the scan is/was executed

### ISSUE THREAD

**Issue by n1ckl0sk0rtge** [IBM/sonar-cryptography#44]
## Extend logging capabilities for the scanner:
- log total amount of detected cryptographic assest after the scan
- log asset name when detected
- log where the `cbom.json` is saved

**Comment by yashathwani** [comment]
Can i work on this ?

**Comment by n1ckl0sk0rtge** [comment]
@yashathwani sure, feel free to add logging capabilities and make a pr.
